- results:
    folder: /home/kartal/Desktop/dersler/tum_gr/dimitris_plotter
    lib_versions:
      pmdk:
        - pmembench_map
      wrappers_only:
        - pmembench_map
      asan:
        - pmembench_map
      safepm:
        - pmembench_map

- plot:
    plot_type: bar
    benchmarks:
      - map_insert
      - map_get
      - map_remove
    y_axis: ops-per-second[1/sec]
    x_axis: type
    variants:
      - ops-per-thread
    plot_folder: /home/kartal/Desktop/dersler/tum_gr/dimitris_plotter/plots
