- results:
    folder: .
    lib_versions:
      pmdk:
        - pmemkv
      asan:
        - pmemkv
      safepm:
        - pmemkv

- plot:
    plot_type: bar
    overhead_annot: false
    benchmarks:
      - delete_random
      - delete_seq
      - randomreadwrite50
      - randomreadwrite95
      - read_random
      - read_seq
    y_axis: ops/sec
    x_axis: Threads
    variants:
      - Entries
    plot_folder: plots/pmemkv
